const express = require('express');
const path = require('path');
const db = require('./db');
const { syncAll, scheduleSync } = require('./sync-data');
const app = express();
const port = Number(process.env.PORT || 3000);
const ESPN = { nfl: 'football/nfl', nba: 'basketball/nba', nhl: 'hockey/nhl', mlb: 'baseball/mlb', 'premier-league': 'soccer/eng.1', tennis: 'tennis/atp' };
app.use(express.json()); app.use(express.static(path.join(__dirname, 'public')));
const sport = db.prepare('SELECT * FROM sports WHERE key=?');
const byName = db.prepare('SELECT p.*,r.rating,r.matches_played FROM participants p JOIN ratings r ON r.participant_id=p.id WHERE p.sport_id=? AND lower(p.name)=lower(?)');
const byId = db.prepare('SELECT p.*,r.rating,r.matches_played FROM participants p JOIN ratings r ON r.participant_id=p.id WHERE p.id=?');
const list = db.prepare('SELECT p.id,p.name,p.short_name,p.gender,r.rating,r.matches_played FROM participants p JOIN ratings r ON r.participant_id=p.id WHERE p.sport_id=? ORDER BY r.rating DESC,p.name');
const add = db.prepare('INSERT INTO participants(sport_id,name,short_name) VALUES (?,?,?)'); const addRating = db.prepare('INSERT INTO ratings(participant_id,rating) VALUES (?,1500)');
function getSport(key,res){const s=sport.get(key);if(!s){res.status(404).json({error:`Unknown sport: ${key}`});return null}return s}
function participant(s,name){name=String(name||'').trim().replace(/\s+/g,' ');if(!name||name.length>80)return null;let p=byName.get(s.id,name);if(p)return p;const id=add.run(s.id,name,name).lastInsertRowid;addRating.run(id);return byId.get(id)}
function eloExpected(a,b){return 1/(1+10**((b-a)/400))}
function probabilities(s,a,b){if(s.key==='tennis'){const home=eloExpected(a.rating,b.rating);return{home,draw:0,away:1-home,model:'Tennis Elo'}}const homeForm=Math.max(1,Math.min(99,50+(a.rating-b.rating)/12+35/8));const home=homeForm/100; if(!s.supports_draw)return{home,draw:0,away:1-home,model:'Team form baseline'};const draw=Math.min(.3,.16+Math.abs(home-.5)*.04);return{home:(1-draw)*home,draw,away:(1-draw)*(1-home),model:'Team form baseline'}}
function american(p){if(!p)return null;const n=p>=.5?-Math.round(100*p/(1-p)):Math.round(100*(1-p)/p);return{decimal:Number((1/p).toFixed(2)),american:n>0?`+${n}`:`${n}`}}
async function json(url){const r=await fetch(url,{headers:{'user-agent':'EdgePlay/1.0'}});if(!r.ok)throw Error(`ESPN ${r.status}`);return r.json()}
function event(e){const c=e.competitions?.[0],x=c?.competitors||[],h=x.find(v=>v.homeAway==='home')||x[0],a=x.find(v=>v.homeAway==='away')||x[1],st=e.status?.type||{};return{id:e.id,name:e.name,date:e.date,state:st.state||'pre',status:st.shortDetail||st.detail||'Scheduled',completed:!!st.completed,home:h&&{name:h.team?.displayName||h.athlete?.displayName||'Home',score:h.score??'-',logo:h.team?.logo},away:a&&{name:a.team?.displayName||a.athlete?.displayName||'Away',score:a.score??'-',logo:a.team?.logo}}}
function classifyPlay(p){const t=(p.text||p.shortText||'').toLowerCase();if(/strike|ball|walk|pitch|at bat|inning/.test(t))return'baseball';if(/pass|quarterback|touchdown|rush|punt|interception|field goal/.test(t))return'football';if(/goal|shot|save|power play|penalty/.test(t))return'hockey';if(/three|dunk|foul|rebound|assist|turnover|free throw/.test(t))return'basketball';if(/goal|corner|yellow card|red card|substitution|offside/.test(t))return'soccer';if(/ace|set|game|break point/.test(t))return'tennis';return'general'}
app.get('/api/health',(_,r)=>r.json({ok:true})); app.get('/api/sports',(_,r)=>r.json(db.prepare('SELECT key,name,kind,supports_draw FROM sports ORDER BY name').all()));
app.get('/api/participants',(q,r)=>{const s=getSport(q.query.sport,r);if(s)r.json(list.all(s.id))});app.get('/api/leaderboard',(q,r)=>{const s=getSport(q.query.sport||'tennis',r);if(s)r.json({sport:s.key,participants:list.all(s.id)})});
app.get('/api/scores',async(q,r)=>{const key=q.query.sport||'nba';if(!ESPN[key])return r.status(400).json({error:'Unsupported score sport'});try{const d=await json(`https://site.api.espn.com/apis/site/v2/sports/${ESPN[key]}/scoreboard`);r.json({sport:key,updatedAt:new Date().toISOString(),events:(d.events||[]).map(event)})}catch(e){r.status(502).json({error:'Live scores unavailable',detail:e.message})}});
app.get('/api/play-by-play',async(q,r)=>{const key=q.query.sport||'nba',id=String(q.query.event||'');if(!ESPN[key]||!id)return r.status(400).json({error:'Sport and event are required'});try{const d=await json(`https://site.api.espn.com/apis/site/v2/sports/${ESPN[key]}/summary?event=${encodeURIComponent(id)}`);const plays=(d.plays||[]).slice().reverse().map(p=>({clock:p.clock,period:p.period?.number||p.period,text:p.text||p.shortText||'Game update',scoring:!!p.scoring,kind:classifyPlay(p)}));const teams=d.header?.competitions?.[0]?.competitors||[];r.json({name:teams.map(x=>x.team?.displayName||x.athlete?.displayName).join(' vs ')||'Play-by-play',plays})}catch(e){r.status(502).json({error:'Play-by-play unavailable',detail:e.message})}});
app.get('/api/matches',(q,r)=>{const s=getSport(q.query.sport||'tennis',r);if(!s)return;const rows=db.prepare('SELECT m.id,m.status,h.name home_name,a.name away_name FROM matches m JOIN participants h ON h.id=m.home_participant_id JOIN participants a ON a.id=m.away_participant_id WHERE m.sport_id=? ORDER BY m.id DESC LIMIT 50').all(s.id);r.json(rows.map(x=>({id:x.id,status:x.status,home:{name:x.home_name},away:{name:x.away_name}}))) });
app.post('/api/predict',(q,r)=>{const s=getSport(q.body?.sport,r);if(!s)return;const h=participant(s,q.body?.home),a=participant(s,q.body?.away);if(!h||!a||h.id===a.id)return r.status(400).json({error:'Enter two different competitors'});const p=probabilities(s,h,a);const m=db.prepare('INSERT INTO matches(sport_id,home_participant_id,away_participant_id,scheduled_at) VALUES(?,?,?,?)').run(s.id,h.id,a.id,new Date().toISOString());const id=db.prepare('INSERT INTO predictions(match_id,sport_id,home_probability,draw_probability,away_probability,model_version) VALUES(?,?,?,?,?,?)').run(m.lastInsertRowid,s.id,p.home,p.draw,p.away,p.model).lastInsertRowid;r.json({id,matchId:m.lastInsertRowid,sport:s.key,home:h.name,away:a.name,probabilities:p,odds:{home:american(p.home),draw:american(p.draw),away:american(p.away)},model:p.model});});
app.get('*',(_,r)=>r.sendFile(path.join(__dirname,'public','index.html')));
app.listen(port,()=>{console.log(`EdgePlay on ${port}`);syncAll().catch(console.error);scheduleSync(Math.max(5,Number(process.env.SYNC_INTERVAL_MINUTES||30))*60000)});
